In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [9]:
df

,Random,Id,Indication,Diabetes,IHD,Hypertension,Arrhythmia,History,IPSI,Contra,label
0,0.602437,218242,A-F,no,no,yes,no,no,78.0,20,NoRisk
1,0.602437,159284,TIA,no,no,no,no,no,70.0,60,NoRisk
2,0.602437,106066,A-F,no,yes,yes,no,no,95.0,40,Risk
3,0.128157,229592,TIA,no,no,yes,no,no,90.0,85,Risk
4,0.676862,245829,CVA,no,no,no,no,no,70.0,20,NoRisk
...,...,...,...,...,...,...,...,...,...,...,...
1515,0.391440,93406,A-F,no,yes,no,no,no,76.0,60,NoRisk
1516,0.253504,121814,A-F,no,no,yes,yes,no,90.0,75,Risk
1517,0.620373,101754,TIA,no,no,yes,no,no,75.0,20,NoRisk
1518,0.639342,263836,A-F,no,yes,no,no,no,70.0,45,NoRisk
1519,0.634922,254941,CVA,no,no,no,no,no,60.0,20,NoRisk

In [14]:
df[["Diabetes", "Contra", "IHD"]]

     Diabetes Contra  IHD
0          no    20    no
1          no    60    no
2          no     40  yes
3          no     85   no
4          no    20    no
...       ...    ...  ...
1515       no    60   yes
1516       no     75   no
1517       no    20    no
1518       no    45   yes
1519       no    20    no

[1520 rows x 3 columns]

In [29]:
df.iloc[472]

Random          0.888968
Id                209878
Indication           A-F
Diabetes              no
IHD                  yes
Hypertension         yes
Arrhythmia            no
History               no
IPSI                  85
Contra                75
label               Risk
Name: 472, dtype: object

In [30]:
df.iloc[[472, 0]]

,Random,Id,Indication,Diabetes,IHD,Hypertension,Arrhythmia,History,IPSI,Contra,label
472,0.888968,209878,A-F,no,yes,yes,no,no,85.0,75,Risk
0,0.602437,218242,A-F,no,no,yes,no,no,78.0,20,NoRisk

In [40]:
df.iloc[100:200]

,Random,Id,Indication,Diabetes,IHD,Hypertension,Arrhythmia,History,IPSI,Contra,label
100,0.704235,192025,CVA,no,yes,yes,no,no,80.0,20,NoRisk
101,0.207456,113046,ASx,yes,no,yes,no,no,80.0,80,Risk
102,0.120481,188606,CVA,no,no,no,no,no,80.0,20,NoRisk
103,0.583807,278178,TIA,no,no,yes,no,no,71.0,20,NoRisk
104,0.655518,217261,CVA,no,yes,yes,yes,no,90.0,100,Risk
...,...,...,...,...,...,...,...,...,...,...,...
195,0.999448,252619,A-F,no,no,yes,no,no,75.0,15,NoRisk
196,0.970781,202122,TIA,no,yes,no,no,no,80.0,51,NoRisk
197,0.971190,219435,TIA,yes,yes,no,no,no,70.0,70,Risk
198,0.970781,276056,CVA,yes,yes,yes,no,no,75.0,100,Risk
199,0.458511,290124,A-F,no,yes,yes,no,no,75.0,30,Risk

In [ ]:
df.iloc[[]]